### ISSUE TITLE
Inaccessible interfaces

### ISSUE THREAD

**Issue by plugandplay** [jklingsporn/vertx-push-onesignal#1]
I try to use this project in my own vertx application by getting the dependency described in the doc:
```
<dependency>
    <groupId>io.github.jklingsporn</groupId>
    <artifactId>vertx-push-onesignal</artifactId>
    <version>1.0.0</version>
</dependency>
```

I just copied the following snippet in my source code, replacing `appId` and `restApiKey` with mine, but it doesn't compile:
```
PushClient.create(vertx, "appId", "restApiKey")
            .withContent(new JsonObject()
                .put("en", "English Content.")
                .put("de","Deutscher Inhalt."))
            //all users should receive this
            .targetBySegments(Segments.ALL)
            .sendNow(h -> {
                if (h.succeeded()) {
                    System.err.println(h.result().encodePrettily());
                } else {
                    h.cause().printStackTrace();
                }
            });
```

The problem is that `sendNow` method is not accessible because the `SendStep` interface has the default visibility.

To reproduce this bug, just put `Examples.java` in an other package (`com.issue` for example).
You can see that some other compilation errors exist with `targetByFilter` and `addOptions` calls.

**Comment by jklingsporn** [comment]
Thank you for your observation. I increased visibility to public and moved Examples class to a separate folder. I'll build a new version and put it onto mavencentral asap.

**Comment by plugandplay** [comment]
Thanks!

**Comment by jklingsporn** [comment]
Release 1.1.0 is deployed to maven central. It might take a while until it is available.
