### ISSUE TITLE
how to push message by use proxy 

### ISSUE THREAD

**Issue by Rekoe** [jklingsporn/vertx-push-onesignal#4]
i need push message by use proxy .how to do it ?
thanks

**Comment by jklingsporn** [comment]
You mean you need to set the ProxyOptions in the HttpClient? Currently that is not possible.

**Comment by Rekoe** [comment]
yes

**Comment by jklingsporn** [comment]
I could create another constructor with (HttpClient,appId,apiKey). When doing so, I cannot guarantee however that SSL is enabled.

**Comment by Rekoe** [comment]
ok ,after you do that i can have a try

**Comment by Rekoe** [comment]
I find this method
https://github.com/vert-x3/vertx-examples/blob/master/core-examples/src/main/java/io/vertx/example/core/http/proxy/Proxy.java
@jklingsporn
