### ISSUE TITLE
the problem about send message use sound demo

### ISSUE THREAD

**Issue by Rekoe** [jklingsporn/vertx-push-onesignal#7]
how to send a message with the filed ios_sound android_sonund

**Comment by jklingsporn** [comment]
SendToSegmentStep (the step before sending) lets you define SendOptions.
e.g. targetBySegments(...).addOptions(new SendOptions(new JsonObject().put("android_sound","someSound")).setCustom("ios_sound", "someSound")).sendNow(...)
should work
